<a href="https://colab.research.google.com/github/meetsomto/dbs/blob/main/programmingWeek5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Function to calculate the BMI,
to accept input of demographic details from users and generate a recommendation.

In [2]:
### BMI	=	body mass index (kg/(m^2) = m/(h)^2
### m	=	mass (in kilograms)
### h	=	height (in meters)

In [11]:
def bmiCalculator():
  m = float(input("Enter your weight in kg: "))
  h = float(input("Enter your height in meters: "))
  bmi = round(m / (h**2), 2) *100

  print("Your Body Mass Index is: {}".format(bmi))

  if bmi > 27:
    print("You need a health checkup")
  else:
    print("You are healthy!")

bmiCalculator()

Enter your weight in kg: 20
Enter your height in meters: 10
Your Body Mass Index is: 20.0
You are healthy!


## Pandas contd


In [13]:
import pandas as pd
import numpy as np

In [14]:
print(pd.__version__)

1.1.4


In [15]:
print(np.__version__)

1.18.5


In [16]:
sample = np.random.rand(6, 4)
print(sample)

[[0.15017569 0.92491801 0.1936783  0.98130988]
 [0.73566306 0.49565388 0.00365321 0.62608692]
 [0.14067112 0.34741536 0.75527209 0.34262239]
 [0.21762375 0.86342364 0.22300401 0.32249034]
 [0.36158733 0.65937813 0.27108969 0.59218513]
 [0.43937856 0.60904997 0.37853945 0.38009482]]


In [17]:
#pandas
data1 = pd.DataFrame(sample, columns=["Cust1", "Cust2", "Cust3", "Cust4"])
print(data1)

      Cust1     Cust2     Cust3     Cust4
0  0.150176  0.924918  0.193678  0.981310
1  0.735663  0.495654  0.003653  0.626087
2  0.140671  0.347415  0.755272  0.342622
3  0.217624  0.863424  0.223004  0.322490
4  0.361587  0.659378  0.271090  0.592185
5  0.439379  0.609050  0.378539  0.380095


In [18]:
data2 = pd.DataFrame(sample, columns=list("abcd"))
print(data2)

          a         b         c         d
0  0.150176  0.924918  0.193678  0.981310
1  0.735663  0.495654  0.003653  0.626087
2  0.140671  0.347415  0.755272  0.342622
3  0.217624  0.863424  0.223004  0.322490
4  0.361587  0.659378  0.271090  0.592185
5  0.439379  0.609050  0.378539  0.380095


In [19]:

    ## Make a dataframe from a dictionary
df2 = pd.DataFrame({
    'A': 1.,
    'B': pd.Timestamp('20130102'),
    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
    'D': np.array([3] * 4, dtype='int32'),
    'E': pd.Categorical(["test", "train", "test", "train"]),
    'F': 'foo'
})
df2


A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [20]:
### Links https://elearning.dbs.ie/pluginfile.php/1248978/mod_resource/content/1/Intro-to-Pandas.html

In [21]:
data5=pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data")
print(data5)

       39          State-gov   77516  ...  40   United-States   <=50K
0      50   Self-emp-not-inc   83311  ...  13   United-States   <=50K
1      38            Private  215646  ...  40   United-States   <=50K
2      53            Private  234721  ...  40   United-States   <=50K
3      28            Private  338409  ...  40            Cuba   <=50K
4      37            Private  284582  ...  40   United-States   <=50K
...    ..                ...     ...  ...  ..             ...     ...
32555  27            Private  257302  ...  38   United-States   <=50K
32556  40            Private  154374  ...  40   United-States    >50K
32557  58            Private  151910  ...  40   United-States   <=50K
32558  22            Private  201490  ...  20   United-States   <=50K
32559  52       Self-emp-inc  287927  ...  40   United-States    >50K

[32560 rows x 15 columns]


In [22]:
# download the data and name the columns
cols = [
    'age', 'workclass', 'fnlwgt', 'education', 'education_num',
    'marital_status', 'occupation', 'relationship', 'ethnicity', 'gender',
    'capital_gain', 'capital_loss', 'hours_per_week', 'country_of_origin',
    'income'
]

data6 = pd.read_csv(
    'http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data',
    names=cols)

print(data6)

       age          workclass  fnlwgt  ... hours_per_week  country_of_origin  income
0       39          State-gov   77516  ...             40      United-States   <=50K
1       50   Self-emp-not-inc   83311  ...             13      United-States   <=50K
2       38            Private  215646  ...             40      United-States   <=50K
3       53            Private  234721  ...             40      United-States   <=50K
4       28            Private  338409  ...             40               Cuba   <=50K
...    ...                ...     ...  ...            ...                ...     ...
32556   27            Private  257302  ...             38      United-States   <=50K
32557   40            Private  154374  ...             40      United-States    >50K
32558   58            Private  151910  ...             40      United-States   <=50K
32559   22            Private  201490  ...             20      United-States   <=50K
32560   52       Self-emp-inc  287927  ...             40      Un

In [25]:
cols = [
        " sepal length",
        "sepal width",
        "petal length",
        "petal width"
        "class"
]

data7 = pd.read_csv(
    'http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',
    names=cols)

print(data7)

      sepal length  sepal width  petal length petal widthclass
5.1            3.5          1.4           0.2      Iris-setosa
4.9            3.0          1.4           0.2      Iris-setosa
4.7            3.2          1.3           0.2      Iris-setosa
4.6            3.1          1.5           0.2      Iris-setosa
5.0            3.6          1.4           0.2      Iris-setosa
..             ...          ...           ...              ...
6.7            3.0          5.2           2.3   Iris-virginica
6.3            2.5          5.0           1.9   Iris-virginica
6.5            3.0          5.2           2.0   Iris-virginica
6.2            3.4          5.4           2.3   Iris-virginica
5.9            3.0          5.1           1.8   Iris-virginica

[150 rows x 4 columns]


In [26]:
data6.head(10)

age          workclass  fnlwgt  ... hours_per_week  country_of_origin  income
0   39          State-gov   77516  ...             40      United-States   <=50K
1   50   Self-emp-not-inc   83311  ...             13      United-States   <=50K
2   38            Private  215646  ...             40      United-States   <=50K
3   53            Private  234721  ...             40      United-States   <=50K
4   28            Private  338409  ...             40               Cuba   <=50K
5   37            Private  284582  ...             40      United-States   <=50K
6   49            Private  160187  ...             16            Jamaica   <=50K
7   52   Self-emp-not-inc  209642  ...             45      United-States    >50K
8   31            Private   45781  ...             50      United-States    >50K
9   42            Private  159449  ...             40      United-States    >50K

[10 rows x 15 columns]

In [29]:
data6.tail() #deafult arg is 5

age      workclass  fnlwgt  ... hours_per_week  country_of_origin  income
32556   27        Private  257302  ...             38      United-States   <=50K
32557   40        Private  154374  ...             40      United-States    >50K
32558   58        Private  151910  ...             40      United-States   <=50K
32559   22        Private  201490  ...             20      United-States   <=50K
32560   52   Self-emp-inc  287927  ...             40      United-States    >50K

[5 rows x 15 columns]

In [30]:
data6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   age                32561 non-null  int64 
 1   workclass          32561 non-null  object
 2   fnlwgt             32561 non-null  int64 
 3   education          32561 non-null  object
 4   education_num      32561 non-null  int64 
 5   marital_status     32561 non-null  object
 6   occupation         32561 non-null  object
 7   relationship       32561 non-null  object
 8   ethnicity          32561 non-null  object
 9   gender             32561 non-null  object
 10  capital_gain       32561 non-null  int64 
 11  capital_loss       32561 non-null  int64 
 12  hours_per_week     32561 non-null  int64 
 13  country_of_origin  32561 non-null  object
 14  income             32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [31]:
data6.values

array([[39, ' State-gov', 77516, ..., 40, ' United-States', ' <=50K'],
       [50, ' Self-emp-not-inc', 83311, ..., 13, ' United-States',
        ' <=50K'],
       [38, ' Private', 215646, ..., 40, ' United-States', ' <=50K'],
       ...,
       [58, ' Private', 151910, ..., 40, ' United-States', ' <=50K'],
       [22, ' Private', 201490, ..., 20, ' United-States', ' <=50K'],
       [52, ' Self-emp-inc', 287927, ..., 40, ' United-States', ' >50K']],
      dtype=object)

In [32]:
# Random samples
sample1 = data6.sample(5)
print(sample1)

       age   workclass  fnlwgt  ... hours_per_week  country_of_origin  income
19478   36     Private  410489  ...             45      United-States   <=50K
25593   27   State-gov  312692  ...             12      United-States   <=50K
12838   17     Private  126771  ...              7      United-States   <=50K
12284   38     Private  186934  ...             40      United-States   <=50K
7584    19           ?  204441  ...             20      United-States   <=50K

[5 rows x 15 columns]


In [35]:
sample2 = data6.sample(5, random_state=2) #the random sample is stored in object 2
print(sample2)

       age     workclass  fnlwgt  ... hours_per_week  country_of_origin  income
16054   42     State-gov  160369  ...             40      United-States    >50K
32382   44     Local-gov  150171  ...             40      United-States   <=50K
10749   39     Local-gov  256997  ...             40      United-States   <=50K
15377   39       Private  147548  ...             40      United-States   <=50K
29660   29   Federal-gov  106179  ...             40      United-States   <=50K

[5 rows x 15 columns]


In [34]:
sample3 = data6.sample(5, random_state=3)
print(sample3)

       age   workclass  fnlwgt  ... hours_per_week  country_of_origin  income
17650   28     Private   51461  ...             40      United-States    >50K
1002    38   State-gov  343642  ...             40      United-States    >50K
11957   49     Private  182752  ...             40      United-States    >50K
4669    38   Local-gov   91711  ...             50      United-States    >50K
28486   24     Private  403671  ...             60      United-States   <=50K

[5 rows x 15 columns]


In [36]:
sample4 = data6.sample(5, random_state=2) #returns the sample saved in object 2
print(sample4)

       age     workclass  fnlwgt  ... hours_per_week  country_of_origin  income
16054   42     State-gov  160369  ...             40      United-States    >50K
32382   44     Local-gov  150171  ...             40      United-States   <=50K
10749   39     Local-gov  256997  ...             40      United-States   <=50K
15377   39       Private  147548  ...             40      United-States   <=50K
29660   29   Federal-gov  106179  ...             40      United-States   <=50K

[5 rows x 15 columns]


In [37]:
data6.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'ethnicity', 'gender',
       'capital_gain', 'capital_loss', 'hours_per_week', 'country_of_origin',
       'income'],
      dtype='object')

In [38]:
# Rename a column
# replace a column name
data6.rename(columns={'country_of_origin': 'native_country'}, inplace=True) #False inplace renames temporarily

data6.head()

age          workclass  fnlwgt  ... hours_per_week  native_country  income
0   39          State-gov   77516  ...             40   United-States   <=50K
1   50   Self-emp-not-inc   83311  ...             13   United-States   <=50K
2   38            Private  215646  ...             40   United-States   <=50K
3   53            Private  234721  ...             40   United-States   <=50K
4   28            Private  338409  ...             40            Cuba   <=50K

[5 rows x 15 columns]

In [39]:
data6.describe()

age        fnlwgt  ...  capital_loss  hours_per_week
count  32561.000000  3.256100e+04  ...  32561.000000    32561.000000
mean      38.581647  1.897784e+05  ...     87.303830       40.437456
std       13.640433  1.055500e+05  ...    402.960219       12.347429
min       17.000000  1.228500e+04  ...      0.000000        1.000000
25%       28.000000  1.178270e+05  ...      0.000000       40.000000
50%       37.000000  1.783560e+05  ...      0.000000       40.000000
75%       48.000000  2.370510e+05  ...      0.000000       45.000000
max       90.000000  1.484705e+06  ...   4356.000000       99.000000

[8 rows x 6 columns]

In [40]:
data6.education.value_counts()

 HS-grad         10501
 Some-college     7291
 Bachelors        5355
 Masters          1723
 Assoc-voc        1382
 11th             1175
 Assoc-acdm       1067
 10th              933
 7th-8th           646
 Prof-school       576
 9th               514
 12th              433
 Doctorate         413
 5th-6th           333
 1st-4th           168
 Preschool          51
Name: education, dtype: int64

In [42]:
# Selecting rows and columns
# By label .loc[]
# By index .iloc[]


data6.iloc[4]

age                                28
workclass                     Private
fnlwgt                         338409
education                   Bachelors
education_num                      13
marital_status     Married-civ-spouse
occupation             Prof-specialty
relationship                     Wife
ethnicity                       Black
gender                         Female
capital_gain                        0
capital_loss                        0
hours_per_week                     40
native_country                   Cuba
income                          <=50K
Name: 4, dtype: object

In [43]:
data6.iloc[0:4]

age          workclass  fnlwgt  ... hours_per_week  native_country  income
0   39          State-gov   77516  ...             40   United-States   <=50K
1   50   Self-emp-not-inc   83311  ...             13   United-States   <=50K
2   38            Private  215646  ...             40   United-States   <=50K
3   53            Private  234721  ...             40   United-States   <=50K

[4 rows x 15 columns]

In [44]:
data6.iloc[:4]

age          workclass  fnlwgt  ... hours_per_week  native_country  income
0   39          State-gov   77516  ...             40   United-States   <=50K
1   50   Self-emp-not-inc   83311  ...             13   United-States   <=50K
2   38            Private  215646  ...             40   United-States   <=50K
3   53            Private  234721  ...             40   United-States   <=50K

[4 rows x 15 columns]

In [45]:
data6.loc[0:3]

age          workclass  fnlwgt  ... hours_per_week  native_country  income
0   39          State-gov   77516  ...             40   United-States   <=50K
1   50   Self-emp-not-inc   83311  ...             13   United-States   <=50K
2   38            Private  215646  ...             40   United-States   <=50K
3   53            Private  234721  ...             40   United-States   <=50K

[4 rows x 15 columns]

In [46]:
#  Filtering

In [47]:
asd = data6[data6.age > 50].head(5)

print(asd)

    age          workclass  fnlwgt  ... hours_per_week  native_country  income
3    53            Private  234721  ...             40   United-States   <=50K
7    52   Self-emp-not-inc  209642  ...             45   United-States    >50K
21   54            Private  302146  ...             20   United-States   <=50K
24   59            Private  109015  ...             40   United-States   <=50K
25   56          Local-gov  216851  ...             40   United-States    >50K

[5 rows x 15 columns]


In [48]:
# Filter for only certain Columns
sample4 = data6.loc[data6.age > 50, ['age', 'education', 'occupation', 'gender', 'income']]
print(sample4)

       age     education          occupation   gender  income
3       53          11th   Handlers-cleaners     Male   <=50K
7       52       HS-grad     Exec-managerial     Male    >50K
21      54       HS-grad       Other-service   Female   <=50K
24      59       HS-grad        Tech-support   Female   <=50K
25      56     Bachelors        Tech-support     Male    >50K
...    ...           ...                 ...      ...     ...
32542   72       HS-grad                   ?     Male   <=50K
32548   65   Prof-school      Prof-specialty     Male   <=50K
32554   53       Masters     Exec-managerial     Male    >50K
32558   58       HS-grad        Adm-clerical   Female   <=50K
32560   52       HS-grad     Exec-managerial   Female    >50K

[6460 rows x 5 columns]


In [50]:
print(sample4.median())

age    58.0
dtype: float64


In [54]:
(data6.age >= 30) & (data6.gender == 'Male')

data6.loc[(data6.age >= 30) & (data6.gender == 'Male') & (data6.age <= 40), :]


Empty DataFrame
Columns: [age, workclass, fnlwgt, education, education_num, marital_status, occupation, relationship, ethnicity, gender, capital_gain, capital_loss, hours_per_week, native_country, income]
Index: []