<a href="https://colab.research.google.com/github/meetsomto/dbs/blob/main/programmingWeek4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ProgrammingWeek4
# Libraries

In [ ]:
#math
#numpy
#pandas
#scikitlearn

In [ ]:
import math

In [ ]:
number1=5
result=math.log(number1)
print(result)

1.6094379124341003


In [ ]:
result1=math.pow(number1, 3)
print(result1)

125.0


In [ ]:
result2=math.sqrt(25)
print(result2)

5.0


In [ ]:
# For Array definition (parse a list to arrays for python)

import numpy as np # as np is conventional
m=np.array([5,6,7])
print(m)

print(type(m))

[5 6 7]
<class 'numpy.ndarray'>


##Vectorization in python using numpy

1. Parallel processing
2. 

In [ ]:
## Array - Single, multidimensional arrays

In [ ]:
n=np.array([[5,6,7], [4,8,9]])
print(n)

[[5 6 7]
 [4 8 9]]


In [ ]:
print(n.shape)

(2, 3)


In [ ]:
age=[34,24,34,53,23,54,67]
marks=[56,45,23,89,64,23,89]

data=np.array([age, marks])

In [ ]:
print(data)

[[34 24 34 53 23 54 67]
 [56 45 23 89 64 23 89]]


In [ ]:
print(data[0,:]) #RC rowindex0 columnindex*

[34 24 34 53 23 54 67]


In [ ]:
print(data[:,0]) # row* columnindex0 

[34 56]


In [ ]:
data*6

array([[204, 144, 204, 318, 138, 324, 402],
       [336, 270, 138, 534, 384, 138, 534]])

In [ ]:
np.sqrt(data)

array([[5.83095189, 4.89897949, 5.83095189, 7.28010989, 4.79583152,
        7.34846923, 8.18535277],
       [7.48331477, 6.70820393, 4.79583152, 9.43398113, 8.        ,
        4.79583152, 9.43398113]])

In [ ]:
o=data.max(axis=0) #  0 =columnwise, 1=rowwise
print(o)

[56 45 34 89 64 54 89]


In [ ]:
# To generate zeros and ones matrix

In [ ]:
np.zeros([3,5], dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.ones([3,5]) #float

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr3=np.random.randint(low=0, high=100, size=24)
print(arr3)

[ 4 89 65 52 70 45 69  5 20 59 21 78 38 80 60 72  1 94 19 88 50 95 55 33]


In [ ]:
arr4=arr3.reshape(3,4,2) # numberofmatrix, rows, column
print(arr4)

[[[ 4 89]
  [65 52]
  [70 45]
  [69  5]]

 [[20 59]
  [21 78]
  [38 80]
  [60 72]]

 [[ 1 94]
  [19 88]
  [50 95]
  [55 33]]]


In [ ]:
arr2= np.array([[1], [3], [2], [0]])
print(arr2)

[[1]
 [3]
 [2]
 [0]]


In [ ]:
arr5= np.array([[1], [3], [5], [0]])

In [ ]:
arr2 @ arr4

ValueError: ignored

In [ ]:
# To check for correlation

In [ ]:
from scipy.stats import pearsonr
result=pearsonr(data[0,:],data[1,:]) #returns pvalue and correlation
print(result) 

In [ ]:
import pandas as pd # used for data visualization wrt ml
data1=pd.DataFrame(data) #rows and column indexes
print(data1)

    0   1   2   3   4   5   6
0  34  24  34  53  23  54  67
1  56  45  23  89  64  23  89


In [ ]:
import numpy as np
import pandas as pd

m=np.array([[2,3,4],[5,6,7]])
data=pd.DataFrame(m)

print(data)

   0  1  2
0  2  3  4
1  5  6  7


In [ ]:
## Make a dataframe from a numpy array
df1 = pd.DataFrame(np.random.randn(6, 4), columns=list('ABCD'))
df1

A         B         C         D
0  1.756980 -1.634215 -0.522751 -1.158114
1  0.023403  0.181911 -0.897819 -2.440540
2 -0.578510 -0.152355  0.844893 -0.446912
3  0.549236  0.561325  0.744786 -0.095672
4  0.440707 -0.035295 -2.082097  0.926769
5  0.146592 -0.064071 -0.616967 -1.204133

In [ ]:
# download the data and name the columns
cols = [
    'age', 'workclass', 'fnlwgt', 'education', 'education_num',
    'marital_status', 'occupation', 'relationship', 'ethnicity', 'gender',
    'capital_gain', 'capital_loss', 'hours_per_week', 'country_of_origin',
    'income'
]

df = pd.read_csv(
    'http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data',
    names=cols)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   age                32561 non-null  int64 
 1   workclass          32561 non-null  object
 2   fnlwgt             32561 non-null  int64 
 3   education          32561 non-null  object
 4   education_num      32561 non-null  int64 
 5   marital_status     32561 non-null  object
 6   occupation         32561 non-null  object
 7   relationship       32561 non-null  object
 8   ethnicity          32561 non-null  object
 9   gender             32561 non-null  object
 10  capital_gain       32561 non-null  int64 
 11  capital_loss       32561 non-null  int64 
 12  hours_per_week     32561 non-null  int64 
 13  country_of_origin  32561 non-null  object
 14  income             32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [ ]:
df.describe()

age        fnlwgt  ...  capital_loss  hours_per_week
count  32561.000000  3.256100e+04  ...  32561.000000    32561.000000
mean      38.581647  1.897784e+05  ...     87.303830       40.437456
std       13.640433  1.055500e+05  ...    402.960219       12.347429
min       17.000000  1.228500e+04  ...      0.000000        1.000000
25%       28.000000  1.178270e+05  ...      0.000000       40.000000
50%       37.000000  1.783560e+05  ...      0.000000       40.000000
75%       48.000000  2.370510e+05  ...      0.000000       45.000000
max       90.000000  1.484705e+06  ...   4356.000000       99.000000

[8 rows x 6 columns]

In [ ]:
df.head(10)

age          workclass  fnlwgt  ... hours_per_week  country_of_origin  income
0   39          State-gov   77516  ...             40      United-States   <=50K
1   50   Self-emp-not-inc   83311  ...             13      United-States   <=50K
2   38            Private  215646  ...             40      United-States   <=50K
3   53            Private  234721  ...             40      United-States   <=50K
4   28            Private  338409  ...             40               Cuba   <=50K
5   37            Private  284582  ...             40      United-States   <=50K
6   49            Private  160187  ...             16            Jamaica   <=50K
7   52   Self-emp-not-inc  209642  ...             45      United-States    >50K
8   31            Private   45781  ...             50      United-States    >50K
9   42            Private  159449  ...             40      United-States    >50K

[10 rows x 15 columns]

In [ ]:
df.tail()

age      workclass  fnlwgt  ... hours_per_week  country_of_origin  income
32556   27        Private  257302  ...             38      United-States   <=50K
32557   40        Private  154374  ...             40      United-States    >50K
32558   58        Private  151910  ...             40      United-States   <=50K
32559   22        Private  201490  ...             20      United-States   <=50K
32560   52   Self-emp-inc  287927  ...             40      United-States    >50K

[5 rows x 15 columns]

In [ ]:
#random sample data
df.sample(5, random_state=42)

age          workclass  fnlwgt  ... hours_per_week  country_of_origin  income
14160   27            Private  160178  ...             38      United-States   <=50K
27048   45          State-gov   50567  ...             40      United-States   <=50K
28868   29            Private  185908  ...             55      United-States    >50K
5667    30            Private  190040  ...             40      United-States   <=50K
7827    29   Self-emp-not-inc  189346  ...             50      United-States   <=50K

[5 rows x 15 columns]

Functions Contd

In [ ]:
#Shopping: order and delivery
def search(item):
  things={"Milk":30, "Water":40}

  if item in things:
    return int(things[item])
  else:
    return 0

  

In [ ]:
def deliver(cost):
  address=input("Please enter your address: ")
  print("Your Product will be delivered at {} and total is {} euro".format(address,round(cost*1.20, 1)))

In [ ]:
def purchase():
  itm=input("Enter item: ")
  basic_cost=search(itm)
  
  if basic_cost==0:
    print("item not in stock")
  else:
    choice=input("Please confirm 'Yes' if you want home delivery: ")
    if choice=="Yes":
      total_cost=1.17*basic_cost

      deliver(total_cost)
    else:
      print("The total price is {} euro with VAT 17%".format(round(1.17*basic_cost, 1)))



In [ ]:
purchase()

Enter item: Coke
item not in stock
